// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuypjjpklumruoljzkeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1eXBqanBrbHVtcnVvbGp6a2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzEwOTQsImV4cCI6MjA2NDUwNzA5NH0.MPhQdilf1zY8vyOrPukSaJDdBaDEartkmSRbRERSAks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);